version: "3.8"

services:
  nginx:
    build:
      dockerfile: ./Dockerfile.nginx
      context: .
    container_name: nginx
    ports: 
      - 80:80
      - 443:443
    networks: 
      - auth-network
    depends_on:
      - auth-api1
      - auth-api2
      - auth-api3
      - redis
      - auth-db

  auth-api1:
    container_name: auth-api1
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - auth-db
      - redis
    volumes:
      - .:/auth
    ports:
      - 5000:5000
    env_file:
      - .env
    entrypoint: ["/bin/bash", "./entrypoints/build_app.sh"]
    networks:
      - auth-network

  auth-api2:
    container_name: auth-api2
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - auth-api1
      - auth-db
      - redis
    volumes:
      - .:/auth
    ports:
      - 5001:5000
    env_file:
      - .env
    entrypoint: ["/bin/bash", "./entrypoints/build_app.sh"]
    networks:
      - auth-network

  auth-api3:
    container_name: auth-api3
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - auth-api2
      - auth-db
      - redis
    volumes:
      - .:/auth
    ports:
      - 5002:5000
    env_file:
      - .env
    entrypoint: ["/bin/bash", "./entrypoints/build_app.sh"]
    networks:
      - auth-network

  redis:
    image: redis
    container_name: ${REDIS_HOST}
    networks:
      - auth-network
    depends_on:
      - auth-db
    ports:
      - 6379:6379
    # expose:      
    #   - 6379

  auth-db:
    container_name: ${POSTGRES_HOST}
    image: postgres
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - auth-db-data:/var/lib/postgresql/data
      - ./entrypoints/db:/docker-entrypoint-initdb.d
    networks:
      - auth-network
  
 
 
volumes:
  auth-db-data:

networks:
  auth-network:
    driver: bridge
